/**
 * OpenNEXT interactive MVP — illustrative market data only.
 *
 * Every quote, supplier, index level, availability figure and SLA below is
 * synthetic. It exists to make the product workflow tangible; it is not a
 * live market feed, an offer to transact, or a representation of any named
 * model vendor's commercial terms. "Official-equivalent value" (OEV) is a
 * normalized demo reference, not transferable vendor credit.
 */

export const demoMeta = Object.freeze({
  dataset: "OpenNEXT illustrative demo market",
  kind: "illustrative-demo-data",
  live: false,
  asOf: "2026-08-20T10:00:00+08:00",
  currency: "USD",
  refreshLabel: "Static demo snapshot",
  sourceLabel: "Synthetic OpenNEXT demo data",
  disclaimer:
    "Illustrative demo data only — not live quotes, verified inventory, investment advice, or an offer to transact.",
  oevDefinition:
    "Official-equivalent value (OEV) is a normalized reference value used in this demo; it is not vendor credit and is not transferable.",
  indexMethod:
    "Demo indices use synthetic Lane A executable depth and settled-trade-like observations. Private RFQ data is excluded from core indices."
});

export const modelMarkets = [
  {
    id: "claude",
    slug: "claude",
    family: "Claude",
    displayName: "Claude Capacity",
    flagshipModel: "Claude Sonnet",
    vendor: "Anthropic",
    indexMultiple: 0.82,
    change7dPct: -1.8,
    exchangeSuppliers: 12,
    executableOevUsd: 184000,
    maxRpm: 2000,
    uptimePct: 99.96,
    p95LatencyMs: 1420,
    status: "Deep market",
    sparkline: [0.86, 0.85, 0.85, 0.84, 0.83, 0.83, 0.82, 0.82, 0.81, 0.82, 0.82, 0.82]
  },
  {
    id: "gpt",
    slug: "gpt",
    family: "GPT",
    displayName: "GPT Capacity",
    flagshipModel: "GPT frontier models",
    vendor: "OpenAI",
    indexMultiple: 0.91,
    change7dPct: -0.6,
    exchangeSuppliers: 15,
    executableOevUsd: 312000,
    maxRpm: 5000,
    uptimePct: 99.98,
    p95LatencyMs: 1510,
    status: "Deep market",
    sparkline: [0.93, 0.93, 0.92, 0.92, 0.92, 0.91, 0.92, 0.91, 0.91, 0.9, 0.91, 0.91]
  },
  {
    id: "gemini",
    slug: "gemini",
    family: "Gemini",
    displayName: "Gemini Capacity",
    flagshipModel: "Gemini Pro / Flash",
    vendor: "Google",
    indexMultiple: 0.76,
    change7dPct: -3.1,
    exchangeSuppliers: 9,
    executableOevUsd: 136000,
    maxRpm: 3000,
    uptimePct: 99.94,
    p95LatencyMs: 980,
    status: "Active",
    sparkline: [0.81, 0.8, 0.8, 0.79, 0.79, 0.78, 0.78, 0.77, 0.77, 0.76, 0.76, 0.76]
  },
  {
    id: "deepseek",
    slug: "deepseek",
    family: "DeepSeek",
    displayName: "DeepSeek Capacity",
    flagshipModel: "DeepSeek reasoning / chat",
    vendor: "DeepSeek + verified hosts",
    indexMultiple: 0.63,
    change7dPct: 1.4,
    exchangeSuppliers: 18,
    executableOevUsd: 428000,
    maxRpm: 8000,
    uptimePct: 99.92,
    p95LatencyMs: 840,
    status: "Most liquid",
    sparkline: [0.61, 0.61, 0.62, 0.62, 0.61, 0.62, 0.62, 0.63, 0.63, 0.62, 0.63, 0.63]
  },
  {
    id: "kimi",
    slug: "kimi",
    family: "Kimi",
    displayName: "Kimi Capacity",
    flagshipModel: "Kimi long-context / agent",
    vendor: "Moonshot AI",
    indexMultiple: 0.71,
    change7dPct: -0.9,
    exchangeSuppliers: 7,
    executableOevUsd: 92000,
    maxRpm: 1800,
    uptimePct: 99.9,
    p95LatencyMs: 1060,
    status: "Active",
    sparkline: [0.73, 0.73, 0.72, 0.72, 0.72, 0.71, 0.72, 0.71, 0.71, 0.71, 0.7, 0.71]
  },
  {
    id: "glm",
    slug: "glm",
    family: "GLM",
    displayName: "GLM Capacity",
    flagshipModel: "GLM general / coding",
    vendor: "Zhipu AI + verified hosts",
    indexMultiple: 0.68,
    change7dPct: 0.7,
    exchangeSuppliers: 8,
    executableOevUsd: 118000,
    maxRpm: 2400,
    uptimePct: 99.91,
    p95LatencyMs: 870,
    status: "Active",
    sparkline: [0.67, 0.67, 0.68, 0.67, 0.68, 0.68, 0.67, 0.68, 0.69, 0.68, 0.68, 0.68]
  }
];

export const gpuOffers = [
  {
    id: "gpu-h100-sin-8",
    accelerator: "H100 SXM 80GB",
    shortName: "H100",
    manufacturer: "NVIDIA",
    category: "GPU",
    memoryGb: 80,
    availableUnits: 64,
    region: "Singapore",
    regionCode: "ap-southeast",
    provider: "Atlas Compute SG",
    lane: "A",
    verified: true,
    price: { amount: 2.34, unit: "GPU-hour", currency: "USD" },
    pricePerChipHour: 2.34,
    change7dPct: -4.1,
    availability: "Available now",
    availabilityPct30d: 97.8,
    nextAvailableAt: "Now",
    term: { type: "On-demand / reserved", minimumHours: 4, maximumDays: 90, reservationDiscountPct: 14 },
    networkLatencyMs: { local: 3, toHongKong: 38, toTokyo: 72 },
    provisionTimeMinutes: 7,
    sla: { uptimePct: 99.9, readyByMinutes: 15, support: "24×7" },
    topology: {
      node: "8× H100 SXM per node",
      interconnect: "NVSwitch",
      fabric: "400G InfiniBand",
      cpuRam: "2× EPYC / 2TB RAM"
    },
    bestFor: ["distributed fine-tuning", "high-throughput inference"],
    sparkline: [2.58, 2.55, 2.5, 2.48, 2.44, 2.42, 2.39, 2.38, 2.36, 2.34]
  },
  {
    id: "gpu-h100-iad-1",
    accelerator: "H100 PCIe 80GB",
    shortName: "H100",
    manufacturer: "NVIDIA",
    category: "GPU",
    memoryGb: 80,
    availableUnits: 22,
    region: "US East (Virginia)",
    regionCode: "us-east",
    provider: "Northstar Cloud",
    lane: "A",
    verified: true,
    price: { amount: 2.08, unit: "GPU-hour", currency: "USD" },
    pricePerChipHour: 2.08,
    change7dPct: -1.7,
    availability: "Available in 18 min",
    availabilityPct30d: 96.3,
    nextAvailableAt: "2026-08-20T10:18:00+08:00",
    term: { type: "On-demand", minimumHours: 1, maximumDays: 30, reservationDiscountPct: 9 },
    networkLatencyMs: { local: 4, toFrankfurt: 86, toSingapore: 219 },
    provisionTimeMinutes: 18,
    sla: { uptimePct: 99.5, readyByMinutes: 25, support: "Business hours + P1" },
    topology: {
      node: "1–4× H100 PCIe per VM",
      interconnect: "PCIe / optional NVLink pairs",
      fabric: "100G Ethernet",
      cpuRam: "EPYC / up to 768GB RAM"
    },
    bestFor: ["batch inference", "single-node fine-tuning"],
    sparkline: [2.2, 2.18, 2.18, 2.16, 2.14, 2.12, 2.11, 2.1, 2.08, 2.08]
  },
  {
    id: "gpu-h200-fra-8",
    accelerator: "H200 SXM 141GB",
    shortName: "H200",
    manufacturer: "NVIDIA",
    category: "GPU",
    memoryGb: 141,
    availableUnits: 40,
    region: "Frankfurt",
    regionCode: "eu-central",
    provider: "Rhein AI Fabric",
    lane: "A",
    verified: true,
    price: { amount: 3.46, unit: "GPU-hour", currency: "USD" },
    pricePerChipHour: 3.46,
    change7dPct: -2.3,
    availability: "Available now",
    availabilityPct30d: 98.6,
    nextAvailableAt: "Now",
    term: { type: "Reserved / dedicated", minimumHours: 24, maximumDays: 180, reservationDiscountPct: 18 },
    networkLatencyMs: { local: 2, toLondon: 18, toVirginia: 88 },
    provisionTimeMinutes: 12,
    sla: { uptimePct: 99.95, readyByMinutes: 20, support: "24×7 enterprise" },
    topology: {
      node: "8× H200 SXM per node",
      interconnect: "NVSwitch",
      fabric: "400G InfiniBand / GPUDirect",
      cpuRam: "2× EPYC / 2.3TB RAM"
    },
    bestFor: ["long-context inference", "large-model fine-tuning"],
    sparkline: [3.64, 3.61, 3.58, 3.56, 3.53, 3.5, 3.49, 3.47, 3.47, 3.46]
  },
  {
    id: "gpu-b200-tyo-8",
    accelerator: "B200 SXM 192GB",
    shortName: "B200",
    manufacturer: "NVIDIA",
    category: "GPU",
    memoryGb: 192,
    availableUnits: 24,
    region: "Tokyo",
    regionCode: "ap-northeast",
    provider: "Kintsugi Compute",
    lane: "A",
    verified: true,
    price: { amount: 5.92, unit: "GPU-hour", currency: "USD" },
    pricePerChipHour: 5.92,
    change7dPct: -5.8,
    availability: "2 nodes today",
    availabilityPct30d: 94.4,
    nextAvailableAt: "2026-08-20T15:00:00+09:00",
    term: { type: "Scheduled reservation", minimumHours: 48, maximumDays: 90, reservationDiscountPct: 16 },
    networkLatencyMs: { local: 2, toSeoul: 34, toSingapore: 74 },
    provisionTimeMinutes: 22,
    sla: { uptimePct: 99.9, readyByMinutes: 30, support: "24×7 enterprise" },
    topology: {
      node: "8× B200 SXM per node",
      interconnect: "NVLink 5 / NVSwitch",
      fabric: "800G fabric",
      cpuRam: "Grace-class host / 3TB RAM"
    },
    bestFor: ["frontier-model training", "dense high-throughput inference"],
    sparkline: [6.48, 6.42, 6.31, 6.24, 6.15, 6.08, 6.02, 5.99, 5.95, 5.92]
  },
  {
    id: "gpu-l40s-hkg-1",
    accelerator: "L40S 48GB",
    shortName: "L40S",
    manufacturer: "NVIDIA",
    category: "GPU",
    memoryGb: 48,
    availableUnits: 96,
    region: "Hong Kong",
    regionCode: "ap-east",
    provider: "HarborStack",
    lane: "A",
    verified: true,
    price: { amount: 0.78, unit: "GPU-hour", currency: "USD" },
    pricePerChipHour: 0.78,
    change7dPct: 0.4,
    availability: "Available now",
    availabilityPct30d: 99.1,
    nextAvailableAt: "Now",
    term: { type: "On-demand", minimumHours: 1, maximumDays: 60, reservationDiscountPct: 12 },
    networkLatencyMs: { local: 2, toSingapore: 36, toShanghai: 31 },
    provisionTimeMinutes: 4,
    sla: { uptimePct: 99.9, readyByMinutes: 10, support: "24×7" },
    topology: {
      node: "1–8× L40S per node",
      interconnect: "PCIe",
      fabric: "100G Ethernet",
      cpuRam: "EPYC / up to 1TB RAM"
    },
    bestFor: ["small-model inference", "embeddings", "image generation"],
    sparkline: [0.76, 0.77, 0.77, 0.78, 0.77, 0.78, 0.78, 0.79, 0.78, 0.78]
  },
  {
    id: "accel-cs3-us-central",
    accelerator: "Cerebras CS-3 (WSE-3)",
    shortName: "Cerebras",
    manufacturer: "Cerebras Systems",
    category: "Wafer-scale accelerator",
    memoryGb: null,
    availableUnits: 6,
    region: "US Central",
    regionCode: "us-central",
    provider: "Velocity Inference",
    lane: "A",
    verified: true,
    price: { amount: 44, unit: "system-hour", currency: "USD" },
    pricePerChipHour: null,
    change7dPct: -1.2,
    availability: "Managed slots available",
    availabilityPct30d: 96.9,
    nextAvailableAt: "2026-08-20T10:10:00+08:00",
    term: { type: "Managed inference slot", minimumHours: 1, maximumDays: 30, reservationDiscountPct: 11 },
    networkLatencyMs: { local: 5, toVirginia: 34, toFrankfurt: 111 },
    provisionTimeMinutes: 10,
    sla: { uptimePct: 99.5, readyByMinutes: 20, support: "24×7 P1" },
    topology: {
      node: "Dedicated CS-3 inference allocation",
      interconnect: "SwarmX fabric",
      fabric: "Managed low-latency endpoint",
      cpuRam: "Provider-managed"
    },
    bestFor: ["latency-sensitive open-model inference", "high token throughput"],
    sparkline: [46.1, 45.8, 45.4, 45.1, 44.9, 44.7, 44.6, 44.3, 44.2, 44]
  }
];

export const providerDepth = {
  claude: [
    {
      id: "claude-depth-1",
      marketId: "claude",
      providerId: "aurora-anthropic-channel",
      providerName: "Aurora Authorized Channel",
      supplyType: "Authorized channel",
      lane: "A",
      priceMultiple: 0.82,
      availableOevUsd: 52000,
      rpm: 2000,
      tpm: 2000000,
      uptimePct: 99.97,
      p95LatencyMs: 1390,
      regions: ["US", "EU"],
      settlement: "Platform gateway · metered",
      sla: "99.9% monthly",
      dataPolicy: "ZDR option",
      quoteFreshnessSeconds: 18,
      executable: true,
      indexEligible: true
    },
    {
      id: "claude-depth-2",
      marketId: "claude",
      providerId: "meridian-inference",
      providerName: "Meridian Inference",
      supplyType: "Enterprise contract capacity",
      lane: "A",
      priceMultiple: 0.835,
      availableOevUsd: 79000,
      rpm: 1500,
      tpm: 1500000,
      uptimePct: 99.96,
      p95LatencyMs: 1450,
      regions: ["US"],
      settlement: "Platform gateway · metered",
      sla: "99.9% monthly",
      dataPolicy: "30-day metadata only",
      quoteFreshnessSeconds: 31,
      executable: true,
      indexEligible: true
    },
    {
      id: "claude-depth-3",
      marketId: "claude",
      providerId: "northbridge-model-services",
      providerName: "Northbridge Model Services",
      supplyType: "Managed inference provider",
      lane: "A",
      priceMultiple: 0.86,
      availableOevUsd: 53000,
      rpm: 900,
      tpm: 1100000,
      uptimePct: 99.93,
      p95LatencyMs: 1520,
      regions: ["APAC", "US"],
      settlement: "Platform gateway · metered",
      sla: "99.5% monthly",
      dataPolicy: "Regional processing",
      quoteFreshnessSeconds: 44,
      executable: true,
      indexEligible: true
    }
  ],
  gpt: [
    {
      id: "gpt-depth-1",
      marketId: "gpt",
      providerId: "vertexline-cloud",
      providerName: "VertexLine Cloud",
      supplyType: "Authorized channel",
      lane: "A",
      priceMultiple: 0.9,
      availableOevUsd: 118000,
      rpm: 5000,
      tpm: 5000000,
      uptimePct: 99.99,
      p95LatencyMs: 1480,
      regions: ["US", "EU", "APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.95% monthly",
      dataPolicy: "ZDR option",
      quoteFreshnessSeconds: 12,
      executable: true,
      indexEligible: true
    },
    {
      id: "gpt-depth-2",
      marketId: "gpt",
      providerId: "quarry-enterprise-ai",
      providerName: "Quarry Enterprise AI",
      supplyType: "Enterprise contract capacity",
      lane: "A",
      priceMultiple: 0.915,
      availableOevUsd: 126000,
      rpm: 3200,
      tpm: 3500000,
      uptimePct: 99.98,
      p95LatencyMs: 1540,
      regions: ["US", "EU"],
      settlement: "Platform gateway · metered",
      sla: "99.9% monthly",
      dataPolicy: "EU residency option",
      quoteFreshnessSeconds: 27,
      executable: true,
      indexEligible: true
    },
    {
      id: "gpt-depth-3",
      marketId: "gpt",
      providerId: "solstice-api-services",
      providerName: "Solstice API Services",
      supplyType: "Managed inference provider",
      lane: "A",
      priceMultiple: 0.94,
      availableOevUsd: 68000,
      rpm: 1800,
      tpm: 2000000,
      uptimePct: 99.94,
      p95LatencyMs: 1610,
      regions: ["APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.5% monthly",
      dataPolicy: "Metadata minimized",
      quoteFreshnessSeconds: 39,
      executable: true,
      indexEligible: true
    }
  ],
  gemini: [
    {
      id: "gemini-depth-1",
      marketId: "gemini",
      providerId: "cloudharbor-ai",
      providerName: "CloudHarbor AI",
      supplyType: "Authorized channel",
      lane: "A",
      priceMultiple: 0.75,
      availableOevUsd: 54000,
      rpm: 3000,
      tpm: 3500000,
      uptimePct: 99.96,
      p95LatencyMs: 930,
      regions: ["US", "APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.9% monthly",
      dataPolicy: "Regional processing",
      quoteFreshnessSeconds: 21,
      executable: true,
      indexEligible: true
    },
    {
      id: "gemini-depth-2",
      marketId: "gemini",
      providerId: "pinnacle-ml-platform",
      providerName: "Pinnacle ML Platform",
      supplyType: "Enterprise contract capacity",
      lane: "A",
      priceMultiple: 0.77,
      availableOevUsd: 49000,
      rpm: 2000,
      tpm: 2400000,
      uptimePct: 99.94,
      p95LatencyMs: 1010,
      regions: ["EU", "US"],
      settlement: "Platform gateway · metered",
      sla: "99.9% monthly",
      dataPolicy: "EU residency option",
      quoteFreshnessSeconds: 36,
      executable: true,
      indexEligible: true
    },
    {
      id: "gemini-depth-3",
      marketId: "gemini",
      providerId: "orbit-inference",
      providerName: "Orbit Inference",
      supplyType: "Managed inference provider",
      lane: "A",
      priceMultiple: 0.79,
      availableOevUsd: 33000,
      rpm: 1200,
      tpm: 1600000,
      uptimePct: 99.91,
      p95LatencyMs: 1070,
      regions: ["APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.5% monthly",
      dataPolicy: "Metadata minimized",
      quoteFreshnessSeconds: 48,
      executable: true,
      indexEligible: true
    }
  ],
  deepseek: [
    {
      id: "deepseek-depth-1",
      marketId: "deepseek",
      providerId: "rhein-ai-fabric",
      providerName: "Rhein AI Fabric",
      supplyType: "Verified model host · H200",
      lane: "A",
      priceMultiple: 0.6,
      availableOevUsd: 172000,
      rpm: 8000,
      tpm: 8500000,
      uptimePct: 99.95,
      p95LatencyMs: 790,
      regions: ["EU"],
      settlement: "Platform endpoint · metered",
      sla: "99.9% monthly",
      dataPolicy: "EU residency",
      quoteFreshnessSeconds: 9,
      executable: true,
      indexEligible: true
    },
    {
      id: "deepseek-depth-2",
      marketId: "deepseek",
      providerId: "harborstack-models",
      providerName: "HarborStack Models",
      supplyType: "Verified model host · H100",
      lane: "A",
      priceMultiple: 0.63,
      availableOevUsd: 146000,
      rpm: 6000,
      tpm: 6500000,
      uptimePct: 99.92,
      p95LatencyMs: 850,
      regions: ["APAC"],
      settlement: "Platform endpoint · metered",
      sla: "99.5% monthly",
      dataPolicy: "APAC residency",
      quoteFreshnessSeconds: 16,
      executable: true,
      indexEligible: true
    },
    {
      id: "deepseek-depth-3",
      marketId: "deepseek",
      providerId: "velocity-inference",
      providerName: "Velocity Inference",
      supplyType: "Verified model host · Cerebras",
      lane: "A",
      priceMultiple: 0.69,
      availableOevUsd: 110000,
      rpm: 4500,
      tpm: 12000000,
      uptimePct: 99.89,
      p95LatencyMs: 190,
      regions: ["US"],
      settlement: "Managed endpoint · metered",
      sla: "99.5% monthly",
      dataPolicy: "US processing",
      quoteFreshnessSeconds: 23,
      executable: true,
      indexEligible: true
    }
  ],
  kimi: [
    {
      id: "kimi-depth-1",
      marketId: "kimi",
      providerId: "eastbridge-ai",
      providerName: "EastBridge AI",
      supplyType: "Authorized channel",
      lane: "A",
      priceMultiple: 0.7,
      availableOevUsd: 42000,
      rpm: 1800,
      tpm: 2500000,
      uptimePct: 99.93,
      p95LatencyMs: 1010,
      regions: ["APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.5% monthly",
      dataPolicy: "APAC processing",
      quoteFreshnessSeconds: 25,
      executable: true,
      indexEligible: true
    },
    {
      id: "kimi-depth-2",
      marketId: "kimi",
      providerId: "lotus-model-services",
      providerName: "Lotus Model Services",
      supplyType: "Enterprise contract capacity",
      lane: "A",
      priceMultiple: 0.72,
      availableOevUsd: 31000,
      rpm: 1200,
      tpm: 1800000,
      uptimePct: 99.9,
      p95LatencyMs: 1080,
      regions: ["APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.5% monthly",
      dataPolicy: "Metadata minimized",
      quoteFreshnessSeconds: 41,
      executable: true,
      indexEligible: true
    },
    {
      id: "kimi-depth-3",
      marketId: "kimi",
      providerId: "northstar-model-gateway",
      providerName: "Northstar Model Gateway",
      supplyType: "Managed inference provider",
      lane: "A",
      priceMultiple: 0.75,
      availableOevUsd: 19000,
      rpm: 800,
      tpm: 1000000,
      uptimePct: 99.86,
      p95LatencyMs: 1180,
      regions: ["US", "APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.0% monthly",
      dataPolicy: "Regional processing",
      quoteFreshnessSeconds: 52,
      executable: true,
      indexEligible: true
    }
  ],
  glm: [
    {
      id: "glm-depth-1",
      marketId: "glm",
      providerId: "jade-ai-services",
      providerName: "Jade AI Services",
      supplyType: "Authorized channel",
      lane: "A",
      priceMultiple: 0.66,
      availableOevUsd: 52000,
      rpm: 2400,
      tpm: 3000000,
      uptimePct: 99.93,
      p95LatencyMs: 820,
      regions: ["APAC"],
      settlement: "Platform gateway · metered",
      sla: "99.5% monthly",
      dataPolicy: "APAC processing",
      quoteFreshnessSeconds: 19,
      executable: true,
      indexEligible: true
    },
    {
      id: "glm-depth-2",
      marketId: "glm",
      providerId: "harborstack-models",
      providerName: "HarborStack Models",
      supplyType: "Verified model host · H100",
      lane: "A",
      priceMultiple: 0.69,
      availableOevUsd: 41000,
      rpm: 1700,
      tpm: 2200000,
      uptimePct: 99.91,
      p95LatencyMs: 880,
      regions: ["APAC"],
      settlement: "Platform endpoint · metered",
      sla: "99.5% monthly",
      dataPolicy: "APAC residency",
      quoteFreshnessSeconds: 33,
      executable: true,
      indexEligible: true
    },
    {
      id: "glm-depth-3",
      marketId: "glm",
      providerId: "redwood-inference",
      providerName: "Redwood Inference",
      supplyType: "Managed inference provider",
      lane: "A",
      priceMultiple: 0.72,
      availableOevUsd: 25000,
      rpm: 1100,
      tpm: 1400000,
      uptimePct: 99.87,
      p95LatencyMs: 970,
      regions: ["US"],
      settlement: "Platform gateway · metered",
      sla: "99.0% monthly",
      dataPolicy: "US processing",
      quoteFreshnessSeconds: 47,
      executable: true,
      indexEligible: true
    }
  ]
};

/**
 * Candidate routes for the demo scheduler.
 * Closed-model APIs intentionally never claim knowledge of the vendor's chip.
 * Disclosed accelerators appear only for open/deployable models hosted through
 * a verified endpoint or a self-hosted capacity offer.
 */
export const routeCatalog = [
  {
    id: "route-claude-sonnet-api",
    label: "Claude Sonnet · enterprise API",
    modelFamily: "Claude",
    model: "Claude Sonnet",
    modelClass: "closed",
    provider: "Aurora Authorized Channel",
    hardware: "Provider-managed (opaque)",
    acceleratorClass: "opaque",
    accessMode: "provider-api",
    region: "US / EU",
    lane: "A",
    indexMultiple: 0.82,
    costPer1M: { input: 2.46, output: 12.3, blended: 6.9 },
    latencyMs: { p50: 740, p95: 1420 },
    throughput: { tokensPerSecond: 78, rpm: 2000 },
    qualityScore: 95,
    uptime: 99.97,
    availability: "online",
    contextWindow: 200000,
    capabilities: ["reasoning", "tools", "vision", "json", "long-context"],
    strengths: ["planning", "document synthesis", "instruction following"],
    taskTypes: ["plan", "reason", "write", "review", "agent"],
    dataResidency: ["US", "EU"],
    sla: "99.9% monthly",
    minCommitment: "None",
    hardwareDisclosed: false,
    routingNote: "Vendor hardware is opaque; selection is based on measured endpoint outcomes."
  },
  {
    id: "route-gpt-frontier-api",
    label: "GPT frontier · enterprise API",
    modelFamily: "GPT",
    model: "GPT frontier model",
    modelClass: "closed",
    provider: "VertexLine Cloud",
    hardware: "Provider-managed (opaque)",
    acceleratorClass: "opaque",
    accessMode: "provider-api",
    region: "US / EU / APAC",
    lane: "A",
    indexMultiple: 0.91,
    costPer1M: { input: 2.75, output: 13.75, blended: 7.7 },
    latencyMs: { p50: 790, p95: 1510 },
    throughput: { tokensPerSecond: 72, rpm: 5000 },
    qualityScore: 96,
    uptime: 99.99,
    availability: "online",
    contextWindow: 256000,
    capabilities: ["reasoning", "tools", "vision", "json", "code"],
    strengths: ["complex reasoning", "tool use", "coding"],
    taskTypes: ["plan", "reason", "code", "review", "agent"],
    dataResidency: ["US", "EU", "APAC"],
    sla: "99.95% monthly",
    minCommitment: "None",
    hardwareDisclosed: false,
    routingNote: "Vendor hardware is opaque; selection is based on measured endpoint outcomes."
  },
  {
    id: "route-gemini-flash-api",
    label: "Gemini Flash · low-latency API",
    modelFamily: "Gemini",
    model: "Gemini Flash",
    modelClass: "closed",
    provider: "CloudHarbor AI",
    hardware: "Provider-managed (opaque)",
    acceleratorClass: "opaque",
    accessMode: "provider-api",
    region: "US / APAC",
    lane: "A",
    indexMultiple: 0.74,
    costPer1M: { input: 0.22, output: 0.88, blended: 0.49 },
    latencyMs: { p50: 250, p95: 520 },
    throughput: { tokensPerSecond: 165, rpm: 3000 },
    qualityScore: 85,
    uptime: 99.96,
    availability: "online",
    contextWindow: 1000000,
    capabilities: ["vision", "json", "long-context", "classification"],
    strengths: ["fast extraction", "multimodal triage", "long-context scan"],
    taskTypes: ["classify", "extract", "summarize", "translate", "vision"],
    dataResidency: ["US", "APAC"],
    sla: "99.9% monthly",
    minCommitment: "None",
    hardwareDisclosed: false,
    routingNote: "Vendor hardware is opaque; selection is based on measured endpoint outcomes."
  },
  {
    id: "route-kimi-agent-api",
    label: "Kimi · long-context agent API",
    modelFamily: "Kimi",
    model: "Kimi long-context model",
    modelClass: "closed",
    provider: "EastBridge AI",
    hardware: "Provider-managed (opaque)",
    acceleratorClass: "opaque",
    accessMode: "provider-api",
    region: "APAC",
    lane: "A",
    indexMultiple: 0.7,
    costPer1M: { input: 0.72, output: 2.82, blended: 1.56 },
    latencyMs: { p50: 510, p95: 1040 },
    throughput: { tokensPerSecond: 96, rpm: 1800 },
    qualityScore: 89,
    uptime: 99.93,
    availability: "online",
    contextWindow: 256000,
    capabilities: ["tools", "json", "long-context", "code"],
    strengths: ["agent workflows", "Chinese content", "long documents"],
    taskTypes: ["research", "summarize", "agent", "write", "code"],
    dataResidency: ["APAC"],
    sla: "99.5% monthly",
    minCommitment: "None",
    hardwareDisclosed: false,
    routingNote: "Vendor hardware is opaque; selection is based on measured endpoint outcomes."
  },
  {
    id: "route-glm-api",
    label: "GLM · balanced API",
    modelFamily: "GLM",
    model: "GLM general model",
    modelClass: "closed",
    provider: "Jade AI Services",
    hardware: "Provider-managed (opaque)",
    acceleratorClass: "opaque",
    accessMode: "provider-api",
    region: "APAC",
    lane: "A",
    indexMultiple: 0.66,
    costPer1M: { input: 0.42, output: 1.65, blended: 0.91 },
    latencyMs: { p50: 410, p95: 840 },
    throughput: { tokensPerSecond: 118, rpm: 2400 },
    qualityScore: 86,
    uptime: 99.93,
    availability: "online",
    contextWindow: 128000,
    capabilities: ["tools", "json", "code", "classification"],
    strengths: ["Chinese content", "coding", "structured extraction"],
    taskTypes: ["classify", "extract", "write", "code", "translate"],
    dataResidency: ["APAC"],
    sla: "99.5% monthly",
    minCommitment: "None",
    hardwareDisclosed: false,
    routingNote: "Vendor hardware is opaque; selection is based on measured endpoint outcomes."
  },
  {
    id: "route-deepseek-h200",
    label: "DeepSeek reasoning · H200",
    modelFamily: "DeepSeek",
    model: "DeepSeek reasoning model",
    modelClass: "open",
    provider: "Rhein AI Fabric",
    hardware: "8× NVIDIA H200 SXM 141GB",
    acceleratorClass: "H200",
    accessMode: "managed-endpoint",
    region: "EU (Frankfurt)",
    lane: "A",
    indexMultiple: 0.6,
    costPer1M: { input: 0.42, output: 1.68, blended: 0.92 },
    latencyMs: { p50: 420, p95: 820 },
    throughput: { tokensPerSecond: 148, rpm: 8000 },
    qualityScore: 92,
    uptime: 99.95,
    availability: "online",
    contextWindow: 128000,
    capabilities: ["reasoning", "json", "code", "self-hostable"],
    strengths: ["reasoning per dollar", "coding", "EU data residency"],
    taskTypes: ["reason", "code", "review", "plan"],
    dataResidency: ["EU"],
    sla: "99.9% monthly",
    minCommitment: "None",
    hardwareDisclosed: true,
    routingNote: "Verified managed endpoint on disclosed H200 capacity."
  },
  {
    id: "route-deepseek-h100",
    label: "DeepSeek chat · H100",
    modelFamily: "DeepSeek",
    model: "DeepSeek chat model",
    modelClass: "open",
    provider: "HarborStack Models",
    hardware: "4× NVIDIA H100 SXM 80GB",
    acceleratorClass: "H100",
    accessMode: "managed-endpoint",
    region: "APAC (Hong Kong)",
    lane: "A",
    indexMultiple: 0.63,
    costPer1M: { input: 0.2, output: 0.8, blended: 0.44 },
    latencyMs: { p50: 310, p95: 690 },
    throughput: { tokensPerSecond: 176, rpm: 6000 },
    qualityScore: 87,
    uptime: 99.92,
    availability: "online",
    contextWindow: 128000,
    capabilities: ["json", "code", "self-hostable", "classification"],
    strengths: ["cost-efficient chat", "coding", "APAC latency"],
    taskTypes: ["classify", "extract", "summarize", "code", "write"],
    dataResidency: ["APAC"],
    sla: "99.5% monthly",
    minCommitment: "None",
    hardwareDisclosed: true,
    routingNote: "Verified managed endpoint on disclosed H100 capacity."
  },
  {
    id: "route-qwen-b200",
    label: "Qwen 32B · B200 fast batch",
    modelFamily: "Qwen",
    model: "Qwen 32B open model",
    modelClass: "open",
    provider: "Kintsugi Compute",
    hardware: "2× NVIDIA B200 SXM 192GB",
    acceleratorClass: "B200",
    accessMode: "managed-endpoint",
    region: "APAC (Tokyo)",
    lane: "A",
    indexMultiple: null,
    costPer1M: { input: 0.14, output: 0.52, blended: 0.29 },
    latencyMs: { p50: 150, p95: 330 },
    throughput: { tokensPerSecond: 305, rpm: 9000 },
    qualityScore: 84,
    uptime: 99.9,
    availability: "online",
    contextWindow: 128000,
    capabilities: ["json", "code", "multilingual", "self-hostable"],
    strengths: ["fast batch", "multilingual extraction", "coding"],
    taskTypes: ["classify", "extract", "summarize", "translate", "code"],
    dataResidency: ["APAC"],
    sla: "99.9% monthly",
    minCommitment: "None",
    hardwareDisclosed: true,
    routingNote: "Verified managed endpoint on disclosed B200 capacity."
  },
  {
    id: "route-qwen-l40s",
    label: "Qwen 8B · L40S economy",
    modelFamily: "Qwen",
    model: "Qwen 8B open model",
    modelClass: "open",
    provider: "HarborStack",
    hardware: "1× NVIDIA L40S 48GB",
    acceleratorClass: "L40S",
    accessMode: "managed-endpoint",
    region: "APAC (Hong Kong)",
    lane: "A",
    indexMultiple: null,
    costPer1M: { input: 0.025, output: 0.095, blended: 0.053 },
    latencyMs: { p50: 88, p95: 190 },
    throughput: { tokensPerSecond: 198, rpm: 14000 },
    qualityScore: 73,
    uptime: 99.9,
    availability: "online",
    contextWindow: 32768,
    capabilities: ["json", "classification", "multilingual", "self-hostable"],
    strengths: ["cheap classification", "routing decisions", "simple extraction"],
    taskTypes: ["classify", "extract", "route", "moderate", "translate"],
    dataResidency: ["APAC"],
    sla: "99.9% monthly",
    minCommitment: "None",
    hardwareDisclosed: true,
    routingNote: "Verified managed endpoint on disclosed L40S capacity."
  },
  {
    id: "route-llama-cerebras",
    label: "Llama 70B · Cerebras ultra-low latency",
    modelFamily: "Llama",
    model: "Llama 70B open model",
    modelClass: "open",
    provider: "Velocity Inference",
    hardware: "Cerebras CS-3 (WSE-3)",
    acceleratorClass: "Cerebras WSE-3",
    accessMode: "managed-endpoint",
    region: "US Central",
    lane: "A",
    indexMultiple: null,
    costPer1M: { input: 0.18, output: 0.72, blended: 0.4 },
    latencyMs: { p50: 58, p95: 128 },
    throughput: { tokensPerSecond: 1820, rpm: 4500 },
    qualityScore: 85,
    uptime: 99.89,
    availability: "online",
    contextWindow: 128000,
    capabilities: ["json", "tools", "self-hostable", "low-latency"],
    strengths: ["interactive latency", "rapid drafting", "high token throughput"],
    taskTypes: ["interactive", "summarize", "draft", "agent", "stream"],
    dataResidency: ["US"],
    sla: "99.5% monthly",
    minCommitment: "None",
    hardwareDisclosed: true,
    routingNote: "Open model on a verified Cerebras managed endpoint; optimized for latency-sensitive steps."
  },
  {
    id: "route-embedding-l40s",
    label: "Open embedding · L40S",
    modelFamily: "Open embeddings",
    model: "Multilingual embedding model",
    modelClass: "open",
    provider: "HarborStack",
    hardware: "1× NVIDIA L40S 48GB",
    acceleratorClass: "L40S",
    accessMode: "managed-endpoint",
    region: "APAC (Hong Kong)",
    lane: "A",
    indexMultiple: null,
    costPer1M: { input: 0.012, output: 0, blended: 0.012 },
    latencyMs: { p50: 31, p95: 68 },
    throughput: { tokensPerSecond: 6100, rpm: 30000 },
    qualityScore: 82,
    uptime: 99.94,
    availability: "online",
    contextWindow: 8192,
    capabilities: ["embeddings", "multilingual", "self-hostable"],
    strengths: ["retrieval", "semantic search", "deduplication"],
    taskTypes: ["embed", "retrieve", "cluster"],
    dataResidency: ["APAC"],
    sla: "99.9% monthly",
    minCommitment: "None",
    hardwareDisclosed: true,
    routingNote: "Verified embedding endpoint on disclosed L40S capacity."
  }
];

export const rfqExamples = [
  {
    id: "RFQ-M-2048",
    title: "Claude capacity · 30-day enterprise burst",
    market: "Model Capacity",
    lane: "Private RFQ",
    visibility: "Private · invited suppliers only",
    status: "6 responses",
    buyer: "Anonymized enterprise buyer",
    request: {
      family: "Claude",
      oevUsd: 100000,
      durationDays: 30,
      minimumTpm: 2000000,
      minimumRpm: 1200,
      region: "US",
      requiredSla: "99.9%",
      dataPolicy: "ZDR preferred"
    },
    indicativeRange: { lowMultiple: 0.79, highMultiple: 0.87 },
    matchedSuppliers: 6,
    nextStep: "Capacity test",
    broker: "OpenNEXT Broker Desk · B-017",
    publicInventory: false,
    indexEligible: false,
    illustrative: true
  },
  {
    id: "RFQ-G-1187",
    title: "256× H100 cluster · 90-day reservation",
    market: "GPU Capacity",
    lane: "Private RFQ",
    visibility: "Private · qualified operators only",
    status: "4 responses",
    buyer: "Anonymized model host",
    request: {
      accelerator: "H100 SXM 80GB",
      units: 256,
      durationDays: 90,
      region: "Singapore preferred",
      topology: "32 nodes × 8 GPU · NVSwitch",
      network: "400G InfiniBand",
      requiredSla: "99.95%"
    },
    indicativeRange: { lowPricePerGpuHour: 1.84, highPricePerGpuHour: 2.28 },
    matchedSuppliers: 4,
    nextStep: "Topology validation",
    broker: "OpenNEXT Broker Desk · B-004",
    publicInventory: false,
    indexEligible: false,
    illustrative: true
  },
  {
    id: "RFQ-H-0731",
    title: "Hybrid inference stack · cost and latency target",
    market: "Model + Accelerator Capacity",
    lane: "Private RFQ",
    visibility: "Private · curated providers",
    status: "Draft",
    buyer: "Anonymized AI application company",
    request: {
      monthlyTokens: 18000000000,
      workloads: ["agent planning", "retrieval", "classification", "interactive generation"],
      latencyTargetP95Ms: 900,
      regions: ["APAC", "US"],
      budgetUsd: 78000,
      termDays: 60
    },
    indicativeRange: { projectedSavingsPctLow: 28, projectedSavingsPctHigh: 41 },
    matchedSuppliers: 0,
    nextStep: "Publish to curated network",
    broker: "Unassigned",
    publicInventory: false,
    indexEligible: false,
    illustrative: true
  }
];

const indexDates = [
  "2026-08-07",
  "2026-08-08",
  "2026-08-09",
  "2026-08-10",
  "2026-08-11",
  "2026-08-12",
  "2026-08-13",
  "2026-08-14",
  "2026-08-15",
  "2026-08-16",
  "2026-08-17",
  "2026-08-18",
  "2026-08-19",
  "2026-08-20"
];

const series = (values) => indexDates.map((date, index) => ({ date, value: values[index] }));

export const indexSeries = {
  modelCapacity: {
    unit: "× official-equivalent reference",
    methodology: "Synthetic Lane A executable observations only",
    confidence: "Demo",
    series: {
      claude: series([0.87, 0.86, 0.86, 0.85, 0.85, 0.85, 0.84, 0.84, 0.83, 0.83, 0.82, 0.81, 0.82, 0.82]),
      gpt: series([0.94, 0.94, 0.93, 0.93, 0.92, 0.92, 0.92, 0.92, 0.91, 0.91, 0.9, 0.91, 0.91, 0.91]),
      gemini: series([0.82, 0.81, 0.81, 0.8, 0.79, 0.79, 0.78, 0.78, 0.77, 0.77, 0.77, 0.76, 0.76, 0.76]),
      deepseek: series([0.61, 0.61, 0.61, 0.62, 0.62, 0.61, 0.62, 0.62, 0.63, 0.63, 0.62, 0.63, 0.63, 0.63]),
      kimi: series([0.73, 0.73, 0.72, 0.72, 0.72, 0.72, 0.71, 0.72, 0.71, 0.71, 0.71, 0.7, 0.71, 0.71]),
      glm: series([0.67, 0.67, 0.67, 0.68, 0.67, 0.68, 0.68, 0.67, 0.68, 0.69, 0.68, 0.68, 0.68, 0.68])
    }
  },
  gpuPrice: {
    unit: "USD per accelerator-hour",
    methodology: "Synthetic all-in Lane A executable offer median",
    confidence: "Demo",
    series: {
      h100: series([2.62, 2.59, 2.56, 2.53, 2.5, 2.48, 2.45, 2.43, 2.41, 2.39, 2.37, 2.36, 2.35, 2.34]),
      h200: series([3.72, 3.69, 3.65, 3.62, 3.58, 3.56, 3.53, 3.51, 3.5, 3.49, 3.48, 3.47, 3.46, 3.46]),
      b200: series([6.64, 6.58, 6.49, 6.43, 6.35, 6.27, 6.19, 6.13, 6.08, 6.02, 5.99, 5.96, 5.94, 5.92]),
      l40s: series([0.76, 0.76, 0.77, 0.77, 0.77, 0.78, 0.78, 0.77, 0.78, 0.78, 0.79, 0.78, 0.78, 0.78])
    }
  },
  otcIndicator: {
    unit: "Indicative × OEV",
    methodology: "Synthetic verified RFQ indications; kept separate from core indices",
    confidence: "Low · demo",
    series: {
      claudePrivateRfq: series([0.8, 0.8, 0.81, 0.8, 0.79, 0.8, 0.8, 0.79, 0.8, 0.8, 0.79, 0.8, 0.8, 0.79])
    }
  },
  aiCapacityCurve: [
    {
      order: 1,
      stage: "Wholesale compute",
      benchmark: "H100 SXM",
      displayValue: "$2.34 / GPU·h",
      normalizedValue: 2.34,
      unit: "USD/GPU-hour"
    },
    {
      order: 2,
      stage: "Hosted inference",
      benchmark: "Open 70B model",
      displayValue: "$0.40 / 1M blended tokens",
      normalizedValue: 0.4,
      unit: "USD/1M tokens"
    },
    {
      order: 3,
      stage: "Frontier model capacity",
      benchmark: "Claude Capacity Index",
      displayValue: "0.82× OEV",
      normalizedValue: 0.82,
      unit: "OEV multiple"
    },
    {
      order: 4,
      stage: "End-buyer delivered capacity",
      benchmark: "SLA + routing + settlement",
      displayValue: "0.86× delivered OEV",
      normalizedValue: 0.86,
      unit: "delivered OEV multiple"
    }
  ]
};

export const marketStats = {
  executableOevUsd: modelMarkets.reduce((sum, market) => sum + market.executableOevUsd, 0),
  exchangeModelSuppliers: modelMarkets.reduce((sum, market) => sum + market.exchangeSuppliers, 0),
  verifiedAcceleratorUnits: gpuOffers.reduce((sum, offer) => sum + offer.availableUnits, 0),
  activePrivateRfqs: 18,
  laneAOnlineSuppliers: 47,
  indicativeDailyNotionalUsd: 1260000,
  compositeModelIndex: 0.752,
  compositeChange7dPct: -1.1,
  displayTimestamp: "20 Aug 2026 · 10:00 CST",
  illustrative: true
};

export const getModelMarket = (marketId) => modelMarkets.find((market) => market.id === marketId);

export const getProviderDepth = (marketId) => providerDepth[marketId] || [];

export const getRoute = (routeId) => routeCatalog.find((route) => route.id === routeId);

// Guard the most important truthfulness rule in the scheduler demo.
for (const route of routeCatalog) {
  if (route.modelClass === "closed" && route.hardware !== "Provider-managed (opaque)") {
    throw new Error(`Closed-model route ${route.id} must not claim a specific accelerator.`);
  }
  if (route.modelClass === "closed" && route.hardwareDisclosed !== false) {
    throw new Error(`Closed-model route ${route.id} must set hardwareDisclosed=false.`);
  }
}
