import {
  state, presets, modelMarkets, gpuOffers, providerDepth, routeCatalog, rfqExamples, indexSeries, marketStats,
  money, compactMoney, compactNumber, escapeHtml, modelView, gpuView, modelCard, gpuCard,
  currentPlan, createSchedule, getEligibleRoutes, scheduleInput, formatCost, formatLatency, lineChart
} from "./demo-core.js?v=opennext-20260913-3";

export function renderOverview() {
  const first = modelView(modelMarkets[0]);
  return `<div class="page">
    <div class="page-head"><div><div class="eyebrow">AI Capacity Market</div><h1>The liquidity and execution layer for AI inference capacity</h1><p>Connect retail Model Capacity clearing prices with upstream wholesale GPU Capacity prices in one market, and turn executable depth directly into orchestration inputs.</p></div><div class="page-actions"><button class="secondary-button" type="button" data-route="data">View Market Data</button><button class="primary-button" type="button" data-route="scheduler">✦ Run AI orchestration demo</button></div></div>
    <section class="hero-panel"><div class="hero-copy"><div class="eyebrow">Smart Capacity Routing</div><h2>Do more than choose one model.<span>Decompose the task, then choose the best execution route for each step.</span></h2><p>OpenNEXT considers expected quality, executable capacity, price, latency, region, SLA and hardware fit. Closed models use only verified provider capacity; open models can also select disclosed routes such as H100, H200, B200 or Cerebras.</p><div class="button-row"><button class="primary-button" type="button" data-route="scheduler">Generate an optimized execution plan</button><button class="secondary-button" type="button" data-action="open-demo-guide">View the 4-minute demo flow</button></div></div>
      <div class="hero-side"><div class="hero-side-label"><span>Sample orchestration plan</span><span class="badge badge-blue">Balanced</span></div><div class="hero-route"><div><strong>PII redaction + classification</strong><span>Qwen 32B · L40S</span></div><b>−72% cost</b></div><div class="hero-route"><div><strong>Rapid high-risk screening</strong><span>Llama 70B · Cerebras route</span></div><b>94 ms</b></div><div class="hero-route"><div><strong>Complex synthesis and reporting</strong><span>Claude Sonnet · Provider-managed</span></div><b>Quality 95</b></div><div class="hero-route"><div><strong>Fact verification</strong><span>DeepSeek · H200</span></div><b>Fallback ready</b></div></div></section>
    <div class="metric-grid"><div class="metric-card"><div class="metric-label"><span>Claude Capacity Index</span><span class="badge badge-green">Confidence A</span></div><div class="metric-value">${first.index.toFixed(2)}×</div><div class="metric-context">Official Reference = 1.00× · Lane A only</div></div><div class="metric-card"><div class="metric-label"><span>Verified executable OEV</span><span class="trend-up">+8.4%</span></div><div class="metric-value">${compactMoney.format(marketStats.executableOevUsd)}</div><div class="metric-context">Continuously verified, orderable capacity</div></div><div class="metric-card"><div class="metric-label"><span>H100 GPU Price Index</span><span class="trend-down">−4.1%</span></div><div class="metric-value">$2.34<span style="font-size:10px;color:var(--muted);font-weight:600"> / GPU·h</span></div><div class="metric-context">H100 SXM · Singapore · on-demand</div></div><div class="metric-card"><div class="metric-label"><span>Lane A suppliers</span><span class="trend-up">12 active now</span></div><div class="metric-value">${marketStats.laneAOnlineSuppliers}</div><div class="metric-context">KYB · rights verified · metered · SLA eligible</div></div></div>
    <section class="section"><div class="section-header"><div><h2>Model Capacity</h2><p>Compare model markets first, then open one to inspect exchange-grade provider depth.</p></div><button class="text-link" type="button" data-route="models">View all markets →</button></div><div class="model-grid">${modelMarkets.map(modelCard).join("")}</div></section>
    <section class="section split-grid"><div class="panel"><div class="section-header"><div><h3>AI Capacity Curve</h3><p>From upstream wholesale compute prices to downstream retail Model Capacity clearing prices.</p></div><span class="badge badge-gray">Illustrative</span></div><div class="capacity-curve"><div class="curve-node"><span>Wholesale compute</span><strong>H100 / H200 / B200</strong><em>$2.34 / GPU·h</em></div><div class="curve-arrow">→</div><div class="curve-node"><span>Production layer</span><strong>Inference provider</strong><em>Measured tokens / $</em></div><div class="curve-arrow">→</div><div class="curve-node"><span>Retail clearing</span><strong>Model Capacity</strong><em>${first.index.toFixed(2)}× official</em></div><div class="curve-arrow">→</div><div class="curve-node"><span>Execution</span><strong>End buyer workload</strong><em>Routed by policy</em></div></div></div>
      <div class="panel"><div class="section-header"><div><h3>Two execution lanes</h3><p>Public liquidity and private RFQs are strictly segregated.</p></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Lane A · Exchange-grade</strong><span>Instant Buy · verified depth · SLA · core index</span></div><em>Auto-routing eligible</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Lane B · Private OTC / RFQ</strong><span>Invite-only · test execution · negotiated terms</span></div><em>Not in core index</em></div></div><button class="secondary-button" style="width:100%;margin-top:14px" type="button" data-route="rfq">Open Private RFQ</button></div></section>
  </div>`;
}

export function renderModels() {
  const query = state.modelQuery.trim().toLowerCase();
  const filtered = modelMarkets.filter((model) => { const m = modelView(model); return !query || `${m.name} ${m.family} ${m.provider}`.toLowerCase().includes(query); });
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">Model Capacity</div><h1>Discover executable capacity by model</h1><p>Public availability, provider depth and index data come only from Lane A. Large, long-term or non-standard demand enters a separate Private RFQ.</p></div><div class="page-actions"><button class="secondary-button" type="button" data-route="rfq">Start Private RFQ</button><button class="primary-button" type="button" data-action="instant-buy-first">Instant Buy</button></div></div>
    <div class="filter-bar"><div class="search-field"><input id="modelSearch" class="input" value="${escapeHtml(state.modelQuery)}" placeholder="Search Claude, GPT, Gemini…" /></div><select class="select" style="width:170px"><option>All regions</option><option>US</option><option>Singapore</option><option>EU</option></select><select class="select" style="width:180px"><option>All data policies</option><option>Zero retention</option><option>EU data boundary</option></select><span class="badge badge-green">● Lane A only</span></div>
    ${filtered.length ? `<div class="model-grid">${filtered.map(modelCard).join("")}</div>` : `<div class="panel empty-state"><strong>No matching model markets</strong><p>Adjust the search and try again.</p></div>`}
    <section class="section panel"><div class="section-header"><div><h3>Why not display API keys directly?</h3><p>The traded asset is measurable, revocable and settleable capacity—not an upstream account or credential.</p></div><span class="badge badge-blue">Controlled delivery</span></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Supplier credential stays vaulted</strong><span>OpenNEXT scoped access → gateway → provider → metering</span></div><em>Buyer never receives key</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Non-standard supply stays private</strong><span>KYB → rights verification → test execution → bilateral contract</span></div><em>Private RFQ</em></div></div></section></div>`;
}

export function renderGpus() {
  const regions = [...new Set(gpuOffers.map((item) => gpuView(item).region))];
  const terms = [...new Set(gpuOffers.map((item) => gpuView(item).term))];
  const filtered = gpuOffers.filter((item) => { const g = gpuView(item); return (state.gpuRegion === "all" || g.region === state.gpuRegion) && (state.gpuTerm === "all" || g.term === state.gpuTerm); });
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">GPU Capacity</div><h1>Buy compute by configuration, schedule and workload</h1><p>Verify continuous availability, accelerator count and topology before comparing true total cost. Long-term, large-cluster and custom-network needs enter Private RFQ.</p></div><div class="page-actions"><button class="secondary-button" type="button" data-route="rfq">Large cluster RFQ</button><button class="primary-button" type="button" data-route="scheduler">Recommend by workload</button></div></div>
    <div class="filter-bar"><select id="gpuRegion" class="select" style="width:170px"><option value="all">All regions</option>${regions.map((item) => `<option ${state.gpuRegion === item ? "selected" : ""}>${escapeHtml(item)}</option>`).join("")}</select><select id="gpuTerm" class="select" style="width:190px"><option value="all">All terms</option>${terms.map((item) => `<option ${state.gpuTerm === item ? "selected" : ""}>${escapeHtml(item)}</option>`).join("")}</select><select class="select" style="width:190px"><option>Any availability</option><option>Start now</option><option>Next 24 hours</option><option>7-day continuous</option></select><span class="badge badge-green">● Verified calendar</span></div>
    <div class="gpu-offer-grid">${filtered.map(gpuCard).join("")}</div><section class="section panel"><div class="section-header"><div><h3>Hardware selection boundary</h3><p>The orchestrator selects a specific chip only for deployable open models or supplier-disclosed routes.</p></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Open / hosted route</strong><span>Model + H100 / H200 / B200 / L40S / disclosed Cerebras route</span></div><em>Hardware-aware routing</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Closed frontier API</strong><span>Claude / GPT / Gemini capacity · provider-managed hardware</span></div><em>Route by price, SLA & region</em></div></div></section></div>`;
}

function strategyOption(id, title, caption) {
  return `<button class="strategy-option ${state.scheduler.strategy === id ? "is-active" : ""}" type="button" data-action="set-strategy" data-strategy="${id}"><strong>${title}</strong><span>${caption}</span></button>`;
}

function planGraph(plan) {
  return plan.steps.map((step,index) => {
    const route = step.assignment.route || routeCatalog.find((item) => item.id === step.assignment.routeId) || {};
    const status = state.scheduler.statuses[step.id] || "queued";
    const statusClass = status === "running" ? "is-running" : status === "done" ? "is-done" : status === "fallback" ? "is-fallback" : "";
    return `<article class="task-node ${statusClass}" data-step-node="${escapeHtml(step.id)}"><div class="task-node-top"><span class="task-index">${String(index+1).padStart(2,"0")}</span><span class="task-status" data-step-status="${escapeHtml(step.id)}">${status === "fallback" ? "rerouted" : status}</span></div><h4>${escapeHtml(step.label)}</h4><p>${escapeHtml(step.description)}</p><div class="task-route"><strong data-node-route="${escapeHtml(step.id)}">${escapeHtml(route.model || route.modelFamily)}</strong><span data-node-hardware="${escapeHtml(step.id)}">${escapeHtml(route.hardware || route.deliveryLayer)}</span></div></article>`;
  }).join("");
}

function routeOptions(step) {
  let eligible = [];
  try { eligible = getEligibleRoutes(step, routeCatalog); } catch { eligible = routeCatalog; }
  if (!eligible.some((route) => route.id === step.assignment.routeId)) { const current = routeCatalog.find((route) => route.id === step.assignment.routeId); if (current) eligible.unshift(current); }
  return eligible.map((route) => `<option value="${escapeHtml(route.id)}" ${route.id === step.assignment.routeId ? "selected" : ""}>${escapeHtml(route.label)} · ${escapeHtml(route.hardware)}</option>`).join("");
}

function planTable(plan) {
  return `<div class="route-table-panel"><div class="panel-heading"><h3>Execution targets</h3><p>Any step can be overridden manually; the critical path, cost and quality are recalculated automatically.</p></div><div class="table-wrap" style="border:0;border-radius:0"><table class="data-table"><thead><tr><th>Subtask</th><th>Selected route</th><th>Compute / delivery</th><th>Est. cost</th><th>P95</th><th>Quality</th><th>Decision</th></tr></thead><tbody>${plan.steps.map((step) => { const a = step.assignment; const route = a.route || routeCatalog.find((item) => item.id === a.routeId) || {}; const opaque = route.modelClass === "closed" || String(route.hardware).includes("opaque"); return `<tr><td><span class="strong">${escapeHtml(step.label)}</span><span class="subline">${escapeHtml(step.taskType)} · floor ${step.minQuality}</span></td><td><select class="route-select" data-action="override-route" data-step-id="${escapeHtml(step.id)}">${routeOptions(step)}</select></td><td class="route-cell"><strong>${escapeHtml(route.hardware || route.deliveryLayer)}</strong><span>${opaque ? "Hardware undisclosed · route by outcome" : `${escapeHtml(route.provider)} · disclosed route`}</span></td><td class="numeric strong">${formatCost(a.estimatedCostUSD)}</td><td>${formatLatency(a.estimatedLatencyMs)}</td><td><span class="badge ${a.qualityScore >= 94 ? "badge-purple" : a.qualityScore >= 88 ? "badge-blue" : "badge-gray"}">${a.qualityScore} / 100</span></td><td><button class="why-button" type="button" data-action="explain-route" data-step-id="${escapeHtml(step.id)}">Why?</button></td></tr>`; }).join("")}</tbody></table></div></div>`;
}

function comparison() {
  const plans = ["balanced","cost","latency"].map((strategy) => createSchedule(scheduleInput({ strategy }),routeCatalog));
  const max = Math.max(...plans.map((plan) => plan.metrics.totalCostUSD),.001);
  return `<div class="comparison-panel"><div class="section-header"><div><h3>Compare three strategies instantly</h3><p>Same task and hard constraints; bar length represents relative estimated cost.</p></div><span class="badge badge-gray">Synthetic estimates</span></div><div class="comparison-bars">${plans.map((plan) => `<div class="comparison-row"><span>${({balanced:"Balanced",cost:"Lowest cost",latency:"Lowest latency"})[plan.strategy.id]}</span><div class="comparison-track"><div class="comparison-fill" style="width:${Math.max(6,plan.metrics.totalCostUSD/max*100)}%"></div></div><em>${formatCost(plan.metrics.totalCostUSD)} · ${formatLatency(plan.metrics.criticalPathLatencyMs)} · Q${plan.metrics.qualityScore}</em></div>`).join("")}</div></div>`;
}

function receipt(plan) {
  if (!state.scheduler.completed) return "";
  const event = state.scheduler.events.at(-1) || plan.lastFallbackEvent;
  return `<div class="comparison-panel" style="border-color:#b7dbc9;background:#fbfefc"><div class="section-header"><div><h3>Simulated execution receipt</h3><p>Execution traces, failover and metering are auditable; no real model call is made.</p></div><span class="badge badge-green">Completed</span></div><div class="metric-grid" style="margin-top:10px"><div class="metric-card"><div class="metric-label">Trace ID</div><div class="metric-value" style="font-size:14px">ON-${plan.id.slice(-6).toUpperCase()}</div><div class="metric-context">Policy v${plan.version}</div></div><div class="metric-card"><div class="metric-label">Actual simulated cost</div><div class="metric-value" style="font-size:18px">${formatCost(plan.metrics.totalCostUSD*1.03)}</div><div class="metric-context">Plan ${formatCost(plan.metrics.totalCostUSD)}</div></div><div class="metric-card"><div class="metric-label">Actual critical path</div><div class="metric-value" style="font-size:18px">${formatLatency(plan.metrics.criticalPathLatencyMs*.97)}</div><div class="metric-context">Plan ${formatLatency(plan.metrics.criticalPathLatencyMs)}</div></div><div class="metric-card"><div class="metric-label">Automatic fallback</div><div class="metric-value" style="font-size:18px">${event ? formatLatency(event.totalRecoveryMs) : "None"}</div><div class="metric-context">${event ? `${escapeHtml(event.from?.provider || "Primary")} → ${escapeHtml(event.to?.provider || "Backup")}` : "No incident"}</div></div></div>${event ? `<div class="scheduler-note"><span>↻</span><div><strong>${escapeHtml(event.stepLabel)} recovered automatically.</strong> ${escapeHtml(event.reason)}. Detected in ${event.detectedInMs} ms and rerouted in ${event.reroutedInMs} ms. The event is recorded in the audit log.</div></div>` : ""}<div class="button-row" style="margin-top:12px"><button class="secondary-button compact" type="button" data-action="export-trace">Export redacted Trace</button><button class="primary-button compact" type="button" data-action="reserve-plan">Reserve this capacity</button></div></div>`;
}

export function renderScheduler() {
  const plan = currentPlan(); const m = plan.metrics; const c = m.constraints; const warning = m.warnings?.[0];
  return `<div class="page scheduler-page"><div class="page-head"><div><div class="eyebrow">Smart Orchestrator</div><h1>Task-level model + execution-chip orchestration</h1><p>Decompose complex work first, then match verified capacity step by step. Hard constraints are filtered before optimizing expected quality, cost, latency and reliability.</p></div><div class="page-actions"><span class="badge badge-blue">✦ Explainable policy</span><span class="badge badge-green">Lane A only</span></div></div><div class="scheduler-layout">
    <aside class="scheduler-controls"><div class="control-section"><div class="control-title">Task description <span>Required</span></div><textarea id="schedulerText" class="textarea">${escapeHtml(state.scheduler.text)}</textarea><div class="chip-row">${Object.entries(presets).map(([id,p]) => `<button class="chip ${state.scheduler.preset===id?"is-active":""}" type="button" data-action="set-preset" data-preset="${id}">${p.label}</button>`).join("")}</div></div><div class="control-section"><div class="control-title">Optimization objective <span>Multi-objective</span></div><div class="strategy-options">${strategyOption("balanced","Balanced","Quality / cost / latency")}${strategyOption("cost","Lowest cost","Protect quality floors")}${strategyOption("latency","Lowest latency","Prioritize fast completion")}</div></div><div class="control-section"><div class="range-header"><span>Budget cap</span><output id="budgetOutput">${money.format(state.scheduler.budgetUSD)}</output></div><input id="budgetRange" class="range" type="range" min="0.05" max="5" step="0.05" value="${state.scheduler.budgetUSD}"><div class="range-header"><span>Critical-path deadline</span><output id="deadlineOutput">${state.scheduler.deadlineSeconds} s</output></div><input id="deadlineRange" class="range" type="range" min="5" max="120" step="1" value="${state.scheduler.deadlineSeconds}"><div class="form-field"><label for="schedulerRegion">Data region</label><select id="schedulerRegion" class="select">${["Singapore","US","EU","Global"].map((item)=>`<option ${state.scheduler.region===item?"selected":""}>${item}</option>`).join("")}</select></div></div><button class="primary-button" type="button" data-action="generate-plan">✦ Decompose task and generate plan</button><div class="scheduler-note" style="margin-top:0"><span>ⓘ</span><div><strong>Closed-model boundary:</strong> Claude, GPT and Gemini hardware is provider-managed; this demo never invents an H100 or Cerebras mapping.</div></div></aside>
    <section class="scheduler-results" id="schedulerResults"><div class="scheduler-runbar"><div><strong>${escapeHtml(plan.preset.label)} · ${escapeHtml(plan.strategy.label)}</strong><span>${plan.steps.length} subtasks · ${escapeHtml(plan.id)} · illustrative snapshot</span></div><div class="button-row"><button class="secondary-button compact" type="button" data-action="regenerate-plan">Replan</button><button class="primary-button compact" type="button" data-action="run-simulation" ${state.scheduler.running?"disabled":""}>${state.scheduler.running?"Running…":"▶ Run simulation"}</button></div></div>
      <div class="summary-grid"><div class="summary-card is-highlight"><div class="summary-label"><span>Estimated cost</span><span class="badge badge-blue">Plan</span></div><div class="summary-value">${formatCost(m.totalCostUSD)}</div><div class="summary-context">Baseline ${formatCost(m.baseline.totalCostUSD)}</div></div><div class="summary-card"><div class="summary-label"><span>Critical path P95</span><span class="${c.deadlineMet?"trend-up":"trend-down"}">${c.deadlineMet?"Within SLA":"Over target"}</span></div><div class="summary-value">${formatLatency(m.criticalPathLatencyMs)}</div><div class="summary-context">Target ${state.scheduler.deadlineSeconds} s</div></div><div class="summary-card"><div class="summary-label"><span>Expected quality</span><span class="badge badge-gray">Estimate</span></div><div class="summary-value">${m.qualityScore.toFixed(1)}</div><div class="summary-context">Per-step floors ${c.qualityFloorsMet?"met":"need review"}</div></div><div class="summary-card"><div class="summary-label"><span>Cost saving</span><span class="trend-up">vs all-frontier</span></div><div class="summary-value">${m.savings.costPercent.toFixed(1)}%</div><div class="summary-context">${formatCost(m.savings.costUSD)} estimated saving</div></div></div>
      ${warning?`<div class="scheduler-note"><span>⚠</span><div><strong>Constraint note:</strong> ${escapeHtml(warning)} Relax the deadline or override the route manually.</div></div>`:""}<div class="task-graph-panel"><div class="task-graph-head"><div><h3>Execution DAG</h3><p>Dependencies determine the critical path; parallel steps are not simply added together.</p></div><span class="badge badge-gray">${plan.steps.length} steps · editable</span></div><div class="task-graph">${planGraph(plan)}</div></div>${planTable(plan)}${receipt(plan)}${comparison()}</section></div></div>`;
}

export function renderRfq() {
  const rfq = rfqExamples[0]; const r = rfq.request;
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">Private OTC / RFQ</div><h1>Turn relationship-driven inquiries into an auditable private market</h1><p>Large, long-term or non-standard supply is never presented as public inventory. The platform handles KYB, capacity verification, test execution, quote comparison and controlled delivery.</p></div><div class="page-actions"><span class="badge badge-amber">Not public inventory</span><button class="primary-button" type="button" data-action="new-rfq">Create RFQ</button></div></div><section class="rfq-hero"><div class="rfq-request"><div class="section-header"><div><span class="badge badge-amber">${escapeHtml(rfq.id)}</span><h2 style="margin-top:9px">${escapeHtml(rfq.title)}</h2><p>${escapeHtml(rfq.visibility)} · Illustrative demo</p></div><span class="badge badge-blue">${escapeHtml(rfq.status)}</span></div><div class="rfq-specs"><div class="rfq-spec"><span>Model</span><strong>${escapeHtml(r.family)}</strong></div><div class="rfq-spec"><span>Notional OEV</span><strong>${compactMoney.format(r.oevUsd)}</strong></div><div class="rfq-spec"><span>Term</span><strong>${r.durationDays} days</strong></div><div class="rfq-spec"><span>Throughput</span><strong>${compactNumber.format(r.minimumTpm)} TPM</strong></div><div class="rfq-spec"><span>Region</span><strong>${escapeHtml(r.region)}</strong></div><div class="rfq-spec"><span>Indicative</span><strong>${rfq.indicativeRange.lowMultiple.toFixed(2)}–${rfq.indicativeRange.highMultiple.toFixed(2)}×</strong></div><div class="rfq-spec"><span>Responses</span><strong>${rfq.matchedSuppliers} qualified</strong></div><div class="rfq-spec"><span>Next step</span><strong>${escapeHtml(rfq.nextStep)}</strong></div></div><div class="rfq-progress">${["Demand normalized","Suppliers invited","Quotes received","Capacity test","Contract","Delivery"].map((label,i)=>`<div class="rfq-progress-step ${i<3?"is-done":i===3?"is-active":""}">${label}</div>`).join("")}</div></div>
      <aside class="broker-card"><div class="broker-profile"><div class="broker-avatar">B17</div><div><strong>${escapeHtml(rfq.broker)}</strong><span>KYB verified · mandate on file · commission disclosed</span></div></div><div class="broker-stats"><div class="broker-stat"><span>30D RFQ volume</span><strong>$3.8M</strong></div><div class="broker-stat"><span>Median fill</span><strong>18.4h</strong></div><div class="broker-stat"><span>Test pass</span><strong>92%</strong></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Authorized access only</strong><span>Broker sees only RFQs under buyer mandate.</span></div></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Separate data series</strong><span>Responses never enter core TMCI or public Available.</span></div></div></div><button class="secondary-button" style="width:100%;margin-top:14px" type="button" data-action="open-rfq-responses">View private quotes</button></aside></section>
    <section class="section"><div class="section-header"><div><h2>Active Private RFQs</h2><p>Separate from public market depth and visible only to invited suppliers.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>RFQ</th><th>Market</th><th>Requirement</th><th>Responses</th><th>Indicative</th><th>Status</th><th>Index treatment</th></tr></thead><tbody>${rfqExamples.map((item)=>`<tr><td><span class="strong">${escapeHtml(item.id)}</span><span class="subline">${escapeHtml(item.title)}</span></td><td>${escapeHtml(item.market)}</td><td>${item.request.oevUsd?compactMoney.format(item.request.oevUsd):escapeHtml(item.request.hardware||"Custom capacity")}</td><td>${item.matchedSuppliers}</td><td>${item.indicativeRange?`${item.indicativeRange.lowMultiple.toFixed(2)}–${item.indicativeRange.highMultiple.toFixed(2)}×`:"Private quotes"}</td><td><span class="badge badge-amber">${escapeHtml(item.nextStep||item.status)}</span></td><td><span class="badge badge-gray">Excluded</span></td></tr>`).join("")}</tbody></table></div></section></div>`;
}

export function renderData() {
  const ms = indexSeries.modelCapacity.series; const gs = indexSeries.gpuPrice.series;
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">Market Data</div><h1>TMCI, TGPI and the AI Capacity Curve</h1><p>The core index uses qualified Lane A data only. Private RFQ creates a separate OTC indicator. All charts use illustrative demo data.</p></div><div class="page-actions"><span class="badge badge-gray">${escapeHtml(marketStats.displayTimestamp)}</span></div></div><div class="metric-grid"><div class="metric-card"><div class="metric-label"><span>Claude TMCI</span><span class="badge badge-green">A</span></div><div class="metric-value">${modelView(modelMarkets[0]).index.toFixed(2)}×</div><div class="metric-context">Lane A only</div></div><div class="metric-card"><div class="metric-label"><span>Composite index</span><span class="trend-down">${marketStats.compositeChange7dPct}%</span></div><div class="metric-value">${marketStats.compositeModelIndex.toFixed(3)}×</div><div class="metric-context">Strictly bucketed demo series</div></div><div class="metric-card"><div class="metric-label"><span>H100 TGPI</span><span class="trend-down">−4.1%</span></div><div class="metric-value">$${gs.h100.at(-1).value.toFixed(2)}</div><div class="metric-context">USD / accelerator-hour</div></div><div class="metric-card"><div class="metric-label"><span>Private RFQ notional</span><span class="badge badge-amber">OTC only</span></div><div class="metric-value">${compactMoney.format(marketStats.indicativeDailyNotionalUsd)}</div><div class="metric-context">Never in core index</div></div></div>
    <section class="section chart-grid"><div class="panel"><div class="section-header"><div><h3>Model Capacity Index · 14D</h3><p>Claude (blue) vs GPT (teal) · reference = 1.00×</p></div><span class="badge badge-gray">Demo</span></div>${lineChart(ms.claude,ms.gpt,"×")}</div><div class="panel"><div class="section-header"><div><h3>Index publication gate</h3><p>Show Indicative or No Print when thresholds are not met.</p></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Settled Lane A trade</strong><span>Core index eligible</span></div><em>Highest weight</em></div><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Firm executable quote</strong><span>Depth only</span></div><em>Live depth</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Verified Private RFQ</strong><span>Separate OTC indicator</span></div><em>Never mixed</em></div></div></div></section>
    <section class="section chart-grid"><div class="panel"><div class="section-header"><div><h3>GPU Price Index · 14D</h3><p>H100 (blue) vs H200 (teal) · exact SKU buckets.</p></div><span class="badge badge-gray">USD / h</span></div>${lineChart(gs.h100,gs.h200,"")}</div><div class="panel"><div class="section-header"><div><h3>Methodology metadata</h3><p>Every number includes sample, recency and confidence context.</p></div></div><div class="rfq-specs" style="grid-template-columns:repeat(2,1fr)"><div class="rfq-spec"><span>Window</span><strong>Rolling 7D</strong></div><div class="rfq-spec"><span>Refresh</span><strong>Hourly demo</strong></div><div class="rfq-spec"><span>Statistic</span><strong>Capped VWAP</strong></div><div class="rfq-spec"><span>Cross-check</span><strong>Weighted median</strong></div></div><div class="scheduler-note"><span>ⓘ</span><div>Closed models show only price correlation between GPU and Model Capacity; no claim is made that true cost or margin can be inferred.</div></div></div></section></div>`;
}
