import {
  state, presets, modelMarkets, gpuOffers, providerDepth, routeCatalog, rfqExamples, indexSeries, marketStats,
  money, compactMoney, compactNumber, escapeHtml, modelView, gpuView, modelCard, gpuCard,
  currentPlan, createSchedule, getEligibleRoutes, scheduleInput, formatCost, formatLatency, lineChart
} from "./demo-core.js?v=opennext-20260912-5";

export function renderOverview() {
  const first = modelView(modelMarkets[0]);
  return `<div class="page">
    <div class="page-head"><div><div class="eyebrow">AI Capacity Market</div><h1>AI 推理容量的流动性与执行层</h1><p>用统一市场连接 Model Capacity 的零售清算价格与 GPU Capacity 的上游批发价格，并把可执行深度直接变成智能调度的输入。</p></div><div class="page-actions"><button class="secondary-button" type="button" data-route="data">查看市场数据</button><button class="primary-button" type="button" data-route="scheduler">✦ 运行 AI 调度 Demo</button></div></div>
    <section class="hero-panel"><div class="hero-copy"><div class="eyebrow">Smart Capacity Routing</div><h2>不是只挑一个模型。<span>先拆任务，再为每一步选择最合适的执行路线。</span></h2><p>OpenNEXT 同时考虑预期效果、可执行容量、价格、延迟、区域、SLA 和硬件适配。闭源模型只选择已验证的 Provider Capacity；开放模型则可以进一步选择 H100、H200、B200 或 Cerebras 等已披露执行路线。</p><div class="button-row"><button class="primary-button" type="button" data-route="scheduler">生成优化执行计划</button><button class="secondary-button" type="button" data-action="open-demo-guide">查看 4 分钟演示路径</button></div></div>
      <div class="hero-side"><div class="hero-side-label"><span>示例调度计划</span><span class="badge badge-blue">Balanced</span></div><div class="hero-route"><div><strong>隐私脱敏 + 分类</strong><span>Qwen 32B · L40S</span></div><b>−72% cost</b></div><div class="hero-route"><div><strong>高风险快速筛查</strong><span>Llama 70B · Cerebras route</span></div><b>94 ms</b></div><div class="hero-route"><div><strong>复杂综合与报告</strong><span>Claude Sonnet · Provider-managed</span></div><b>Quality 95</b></div><div class="hero-route"><div><strong>事实校验</strong><span>DeepSeek · H200</span></div><b>Fallback ready</b></div></div></section>
    <div class="metric-grid"><div class="metric-card"><div class="metric-label"><span>Claude Capacity Index</span><span class="badge badge-green">Confidence A</span></div><div class="metric-value">${first.index.toFixed(2)}×</div><div class="metric-context">Official Reference = 1.00× · Lane A only</div></div><div class="metric-card"><div class="metric-label"><span>Verified executable OEV</span><span class="trend-up">+8.4%</span></div><div class="metric-value">${compactMoney.format(marketStats.executableOevUsd)}</div><div class="metric-context">Continuously verified, orderable capacity</div></div><div class="metric-card"><div class="metric-label"><span>H100 GPU Price Index</span><span class="trend-down">−4.1%</span></div><div class="metric-value">$2.34<span style="font-size:10px;color:var(--muted);font-weight:600"> / GPU·h</span></div><div class="metric-context">H100 SXM · Singapore · on-demand</div></div><div class="metric-card"><div class="metric-label"><span>Lane A suppliers</span><span class="trend-up">12 active now</span></div><div class="metric-value">${marketStats.laneAOnlineSuppliers}</div><div class="metric-context">KYB · rights verified · metered · SLA eligible</div></div></div>
    <section class="section"><div class="section-header"><div><h2>Model Capacity</h2><p>先比较模型市场，打开后再看 Exchange-grade provider depth。</p></div><button class="text-link" type="button" data-route="models">查看全部市场 →</button></div><div class="model-grid">${modelMarkets.map(modelCard).join("")}</div></section>
    <section class="section split-grid"><div class="panel"><div class="section-header"><div><h3>AI Capacity Curve</h3><p>从上游算力批发价格到下游模型容量零售清算价格。</p></div><span class="badge badge-gray">Illustrative</span></div><div class="capacity-curve"><div class="curve-node"><span>Wholesale compute</span><strong>H100 / H200 / B200</strong><em>$2.34 / GPU·h</em></div><div class="curve-arrow">→</div><div class="curve-node"><span>Production layer</span><strong>Inference provider</strong><em>Measured tokens / $</em></div><div class="curve-arrow">→</div><div class="curve-node"><span>Retail clearing</span><strong>Model Capacity</strong><em>${first.index.toFixed(2)}× official</em></div><div class="curve-arrow">→</div><div class="curve-node"><span>Execution</span><strong>End buyer workload</strong><em>Routed by policy</em></div></div></div>
      <div class="panel"><div class="section-header"><div><h3>Two execution lanes</h3><p>公开流动性与私域询价严格分池。</p></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Lane A · Exchange-grade</strong><span>Instant Buy · verified depth · SLA · core index</span></div><em>Auto-routing eligible</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Lane B · Private OTC / RFQ</strong><span>Invite-only · test execution · negotiated terms</span></div><em>Not in core index</em></div></div><button class="secondary-button" style="width:100%;margin-top:14px" type="button" data-route="rfq">打开 Private RFQ</button></div></section>
  </div>`;
}

export function renderModels() {
  const query = state.modelQuery.trim().toLowerCase();
  const filtered = modelMarkets.filter((model) => { const m = modelView(model); return !query || `${m.name} ${m.family} ${m.provider}`.toLowerCase().includes(query); });
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">Model Capacity</div><h1>按模型发现可执行容量</h1><p>公开展示的 Available、Provider Depth 与 Index 仅来自 Lane A。大额、长期或非标准需求进入独立 Private RFQ。</p></div><div class="page-actions"><button class="secondary-button" type="button" data-route="rfq">Start Private RFQ</button><button class="primary-button" type="button" data-action="instant-buy-first">Instant Buy</button></div></div>
    <div class="filter-bar"><div class="search-field"><input id="modelSearch" class="input" value="${escapeHtml(state.modelQuery)}" placeholder="搜索 Claude、GPT、Gemini…" /></div><select class="select" style="width:170px"><option>All regions</option><option>US</option><option>Singapore</option><option>EU</option></select><select class="select" style="width:180px"><option>All data policies</option><option>Zero retention</option><option>EU data boundary</option></select><span class="badge badge-green">● Lane A only</span></div>
    ${filtered.length ? `<div class="model-grid">${filtered.map(modelCard).join("")}</div>` : `<div class="panel empty-state"><strong>没有匹配的模型市场</strong><p>调整搜索条件后重试。</p></div>`}
    <section class="section panel"><div class="section-header"><div><h3>为什么不直接展示 API Key？</h3><p>交易对象是可计量、可撤销、可结算的容量，不是上游账户或凭证。</p></div><span class="badge badge-blue">Controlled delivery</span></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Supplier credential stays vaulted</strong><span>OpenNEXT scoped access → gateway → provider → metering</span></div><em>Buyer never receives key</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Non-standard supply stays private</strong><span>KYB → rights verification → test execution → bilateral contract</span></div><em>Private RFQ</em></div></div></section></div>`;
}

export function renderGpus() {
  const regions = [...new Set(gpuOffers.map((item) => gpuView(item).region))];
  const terms = [...new Set(gpuOffers.map((item) => gpuView(item).term))];
  const filtered = gpuOffers.filter((item) => { const g = gpuView(item); return (state.gpuRegion === "all" || g.region === state.gpuRegion) && (state.gpuTerm === "all" || g.term === state.gpuTerm); });
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">GPU Capacity</div><h1>按配置、时间与任务购买算力</h1><p>先验证连续可用时段、卡数和拓扑，再比较真实总价。长租、大集群与定制网络进入 Private RFQ。</p></div><div class="page-actions"><button class="secondary-button" type="button" data-route="rfq">Large cluster RFQ</button><button class="primary-button" type="button" data-route="scheduler">按任务智能推荐</button></div></div>
    <div class="filter-bar"><select id="gpuRegion" class="select" style="width:170px"><option value="all">All regions</option>${regions.map((item) => `<option ${state.gpuRegion === item ? "selected" : ""}>${escapeHtml(item)}</option>`).join("")}</select><select id="gpuTerm" class="select" style="width:190px"><option value="all">All terms</option>${terms.map((item) => `<option ${state.gpuTerm === item ? "selected" : ""}>${escapeHtml(item)}</option>`).join("")}</select><select class="select" style="width:190px"><option>Any availability</option><option>Start now</option><option>Next 24 hours</option><option>7-day continuous</option></select><span class="badge badge-green">● Verified calendar</span></div>
    <div class="gpu-offer-grid">${filtered.map(gpuCard).join("")}</div><section class="section panel"><div class="section-header"><div><h3>硬件选择边界</h3><p>只有可部署开放模型或供应商明确披露的路线，调度器才会选择具体芯片。</p></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Open / hosted route</strong><span>Model + H100 / H200 / B200 / L40S / disclosed Cerebras route</span></div><em>Hardware-aware routing</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Closed frontier API</strong><span>Claude / GPT / Gemini capacity · provider-managed hardware</span></div><em>Route by price, SLA & region</em></div></div></section></div>`;
}

function strategyOption(id, title, caption) {
  return `<button class="strategy-option ${state.scheduler.strategy === id ? "is-active" : ""}" type="button" data-action="set-strategy" data-strategy="${id}"><strong>${title}</strong><span>${caption}</span></button>`;
}

function planGraph(plan) {
  return plan.steps.map((step,index) => {
    const route = step.assignment.route || routeCatalog.find((item) => item.id === step.assignment.routeId) || {};
    const status = state.scheduler.statuses[step.id] || "queued";
    const statusClass = status === "running" ? "is-running" : status === "done" ? "is-done" : status === "fallback" ? "is-fallback" : "";
    return `<article class="task-node ${statusClass}" data-step-node="${escapeHtml(step.id)}"><div class="task-node-top"><span class="task-index">${String(index+1).padStart(2,"0")}</span><span class="task-status" data-step-status="${escapeHtml(step.id)}">${status === "fallback" ? "rerouted" : status}</span></div><h4>${escapeHtml(step.label)}</h4><p>${escapeHtml(step.description)}</p><div class="task-route"><strong data-node-route="${escapeHtml(step.id)}">${escapeHtml(route.model || route.modelFamily)}</strong><span data-node-hardware="${escapeHtml(step.id)}">${escapeHtml(route.hardware || route.deliveryLayer)}</span></div></article>`;
  }).join("");
}

function routeOptions(step) {
  let eligible = [];
  try { eligible = getEligibleRoutes(step, routeCatalog); } catch { eligible = routeCatalog; }
  if (!eligible.some((route) => route.id === step.assignment.routeId)) { const current = routeCatalog.find((route) => route.id === step.assignment.routeId); if (current) eligible.unshift(current); }
  return eligible.map((route) => `<option value="${escapeHtml(route.id)}" ${route.id === step.assignment.routeId ? "selected" : ""}>${escapeHtml(route.label)} · ${escapeHtml(route.hardware)}</option>`).join("");
}

function planTable(plan) {
  return `<div class="route-table-panel"><div class="panel-heading"><h3>Execution targets</h3><p>可人工覆盖某一步；修改后自动重新计算关键路径、成本与质量。</p></div><div class="table-wrap" style="border:0;border-radius:0"><table class="data-table"><thead><tr><th>Subtask</th><th>Selected route</th><th>Compute / delivery</th><th>Est. cost</th><th>P95</th><th>Quality</th><th>Decision</th></tr></thead><tbody>${plan.steps.map((step) => { const a = step.assignment; const route = a.route || routeCatalog.find((item) => item.id === a.routeId) || {}; const opaque = route.modelClass === "closed" || String(route.hardware).includes("opaque"); return `<tr><td><span class="strong">${escapeHtml(step.label)}</span><span class="subline">${escapeHtml(step.taskType)} · floor ${step.minQuality}</span></td><td><select class="route-select" data-action="override-route" data-step-id="${escapeHtml(step.id)}">${routeOptions(step)}</select></td><td class="route-cell"><strong>${escapeHtml(route.hardware || route.deliveryLayer)}</strong><span>${opaque ? "Hardware undisclosed · route by outcome" : `${escapeHtml(route.provider)} · disclosed route`}</span></td><td class="numeric strong">${formatCost(a.estimatedCostUSD)}</td><td>${formatLatency(a.estimatedLatencyMs)}</td><td><span class="badge ${a.qualityScore >= 94 ? "badge-purple" : a.qualityScore >= 88 ? "badge-blue" : "badge-gray"}">${a.qualityScore} / 100</span></td><td><button class="why-button" type="button" data-action="explain-route" data-step-id="${escapeHtml(step.id)}">Why?</button></td></tr>`; }).join("")}</tbody></table></div></div>`;
}

function comparison() {
  const plans = ["balanced","cost","latency"].map((strategy) => createSchedule(scheduleInput({ strategy }),routeCatalog));
  const max = Math.max(...plans.map((plan) => plan.metrics.totalCostUSD),.001);
  return `<div class="comparison-panel"><div class="section-header"><div><h3>三种策略即时对比</h3><p>同一任务、同一硬约束；长度表示相对预计成本。</p></div><span class="badge badge-gray">Synthetic estimates</span></div><div class="comparison-bars">${plans.map((plan) => `<div class="comparison-row"><span>${({balanced:"平衡",cost:"最低成本",latency:"最低延迟"})[plan.strategy.id]}</span><div class="comparison-track"><div class="comparison-fill" style="width:${Math.max(6,plan.metrics.totalCostUSD/max*100)}%"></div></div><em>${formatCost(plan.metrics.totalCostUSD)} · ${formatLatency(plan.metrics.criticalPathLatencyMs)} · Q${plan.metrics.qualityScore}</em></div>`).join("")}</div></div>`;
}

function receipt(plan) {
  if (!state.scheduler.completed) return "";
  const event = state.scheduler.events.at(-1) || plan.lastFallbackEvent;
  return `<div class="comparison-panel" style="border-color:#b7dbc9;background:#fbfefc"><div class="section-header"><div><h3>Simulated execution receipt</h3><p>执行轨迹、故障回退与计量可审计；非真实调用。</p></div><span class="badge badge-green">Completed</span></div><div class="metric-grid" style="margin-top:10px"><div class="metric-card"><div class="metric-label">Trace ID</div><div class="metric-value" style="font-size:14px">ON-${plan.id.slice(-6).toUpperCase()}</div><div class="metric-context">Policy v${plan.version}</div></div><div class="metric-card"><div class="metric-label">Actual simulated cost</div><div class="metric-value" style="font-size:18px">${formatCost(plan.metrics.totalCostUSD*1.03)}</div><div class="metric-context">Plan ${formatCost(plan.metrics.totalCostUSD)}</div></div><div class="metric-card"><div class="metric-label">Actual critical path</div><div class="metric-value" style="font-size:18px">${formatLatency(plan.metrics.criticalPathLatencyMs*.97)}</div><div class="metric-context">Plan ${formatLatency(plan.metrics.criticalPathLatencyMs)}</div></div><div class="metric-card"><div class="metric-label">Automatic fallback</div><div class="metric-value" style="font-size:18px">${event ? formatLatency(event.totalRecoveryMs) : "None"}</div><div class="metric-context">${event ? `${escapeHtml(event.from?.provider || "Primary")} → ${escapeHtml(event.to?.provider || "Backup")}` : "No incident"}</div></div></div>${event ? `<div class="scheduler-note"><span>↻</span><div><strong>${escapeHtml(event.stepLabel)} recovered automatically.</strong> ${escapeHtml(event.reason)}；${event.detectedInMs} ms 检测，${event.reroutedInMs} ms 完成重路由，事件已写入审计记录。</div></div>` : ""}<div class="button-row" style="margin-top:12px"><button class="secondary-button compact" type="button" data-action="export-trace">导出脱敏 Trace</button><button class="primary-button compact" type="button" data-action="reserve-plan">预留这组容量</button></div></div>`;
}

export function renderScheduler() {
  const plan = currentPlan(); const m = plan.metrics; const c = m.constraints; const warning = m.warnings?.[0];
  return `<div class="page scheduler-page"><div class="page-head"><div><div class="eyebrow">Smart Orchestrator</div><h1>任务级「模型 + 执行芯片」智能调度</h1><p>先拆复杂任务，再逐步匹配已验证容量。硬约束先过滤，随后在预期效果、成本、延迟与可靠性之间优化。</p></div><div class="page-actions"><span class="badge badge-blue">✦ Explainable policy</span><span class="badge badge-green">Lane A only</span></div></div><div class="scheduler-layout">
    <aside class="scheduler-controls"><div class="control-section"><div class="control-title">任务描述 <span>Required</span></div><textarea id="schedulerText" class="textarea">${escapeHtml(state.scheduler.text)}</textarea><div class="chip-row">${Object.entries(presets).map(([id,p]) => `<button class="chip ${state.scheduler.preset===id?"is-active":""}" type="button" data-action="set-preset" data-preset="${id}">${p.label}</button>`).join("")}</div></div><div class="control-section"><div class="control-title">优化目标 <span>Multi-objective</span></div><div class="strategy-options">${strategyOption("balanced","平衡","效果 / 成本 / 延迟")}${strategyOption("cost","最低成本","守住质量门槛")}${strategyOption("latency","最低延迟","优先快速完成")}</div></div><div class="control-section"><div class="range-header"><span>预算上限</span><output id="budgetOutput">${money.format(state.scheduler.budgetUSD)}</output></div><input id="budgetRange" class="range" type="range" min="0.05" max="5" step="0.05" value="${state.scheduler.budgetUSD}"><div class="range-header"><span>关键路径时限</span><output id="deadlineOutput">${state.scheduler.deadlineSeconds} s</output></div><input id="deadlineRange" class="range" type="range" min="5" max="120" step="1" value="${state.scheduler.deadlineSeconds}"><div class="form-field"><label for="schedulerRegion">数据区域</label><select id="schedulerRegion" class="select">${["Singapore","US","EU","Global"].map((item)=>`<option ${state.scheduler.region===item?"selected":""}>${item}</option>`).join("")}</select></div></div><button class="primary-button" type="button" data-action="generate-plan">✦ 拆解任务并生成计划</button><div class="scheduler-note" style="margin-top:0"><span>ⓘ</span><div><strong>Closed-model boundary:</strong> Claude / GPT / Gemini 的芯片由服务商管理；这里不会虚构 H100 或 Cerebras 映射。</div></div></aside>
    <section class="scheduler-results" id="schedulerResults"><div class="scheduler-runbar"><div><strong>${escapeHtml(plan.preset.label)} · ${escapeHtml(plan.strategy.label)}</strong><span>${plan.steps.length} subtasks · ${escapeHtml(plan.id)} · illustrative snapshot</span></div><div class="button-row"><button class="secondary-button compact" type="button" data-action="regenerate-plan">重新规划</button><button class="primary-button compact" type="button" data-action="run-simulation" ${state.scheduler.running?"disabled":""}>${state.scheduler.running?"执行中…":"▶ Run simulation"}</button></div></div>
      <div class="summary-grid"><div class="summary-card is-highlight"><div class="summary-label"><span>Estimated cost</span><span class="badge badge-blue">Plan</span></div><div class="summary-value">${formatCost(m.totalCostUSD)}</div><div class="summary-context">Baseline ${formatCost(m.baseline.totalCostUSD)}</div></div><div class="summary-card"><div class="summary-label"><span>Critical path P95</span><span class="${c.deadlineMet?"trend-up":"trend-down"}">${c.deadlineMet?"Within SLA":"Over target"}</span></div><div class="summary-value">${formatLatency(m.criticalPathLatencyMs)}</div><div class="summary-context">Target ${state.scheduler.deadlineSeconds} s</div></div><div class="summary-card"><div class="summary-label"><span>Expected quality</span><span class="badge badge-gray">Estimate</span></div><div class="summary-value">${m.qualityScore.toFixed(1)}</div><div class="summary-context">Per-step floors ${c.qualityFloorsMet?"met":"need review"}</div></div><div class="summary-card"><div class="summary-label"><span>Cost saving</span><span class="trend-up">vs all-frontier</span></div><div class="summary-value">${m.savings.costPercent.toFixed(1)}%</div><div class="summary-context">${formatCost(m.savings.costUSD)} estimated saving</div></div></div>
      ${warning?`<div class="scheduler-note"><span>⚠</span><div><strong>Constraint note:</strong> ${escapeHtml(warning)} 可放宽时限或手动覆盖路线。</div></div>`:""}<div class="task-graph-panel"><div class="task-graph-head"><div><h3>Execution DAG</h3><p>依赖关系用于计算关键路径；并行步骤不会被简单相加。</p></div><span class="badge badge-gray">${plan.steps.length} steps · editable</span></div><div class="task-graph">${planGraph(plan)}</div></div>${planTable(plan)}${receipt(plan)}${comparison()}</section></div></div>`;
}

export function renderRfq() {
  const rfq = rfqExamples[0]; const r = rfq.request;
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">Private OTC / RFQ</div><h1>把关系型询价变成可审计的私域市场</h1><p>大额、长期或非标准供给不会伪装成公开库存。平台完成 KYB、容量验证、测试执行、报价比较与受控交付。</p></div><div class="page-actions"><span class="badge badge-amber">Not public inventory</span><button class="primary-button" type="button" data-action="new-rfq">创建 RFQ</button></div></div><section class="rfq-hero"><div class="rfq-request"><div class="section-header"><div><span class="badge badge-amber">${escapeHtml(rfq.id)}</span><h2 style="margin-top:9px">${escapeHtml(rfq.title)}</h2><p>${escapeHtml(rfq.visibility)} · Illustrative demo</p></div><span class="badge badge-blue">${escapeHtml(rfq.status)}</span></div><div class="rfq-specs"><div class="rfq-spec"><span>Model</span><strong>${escapeHtml(r.family)}</strong></div><div class="rfq-spec"><span>Notional OEV</span><strong>${compactMoney.format(r.oevUsd)}</strong></div><div class="rfq-spec"><span>Term</span><strong>${r.durationDays} days</strong></div><div class="rfq-spec"><span>Throughput</span><strong>${compactNumber.format(r.minimumTpm)} TPM</strong></div><div class="rfq-spec"><span>Region</span><strong>${escapeHtml(r.region)}</strong></div><div class="rfq-spec"><span>Indicative</span><strong>${rfq.indicativeRange.lowMultiple.toFixed(2)}–${rfq.indicativeRange.highMultiple.toFixed(2)}×</strong></div><div class="rfq-spec"><span>Responses</span><strong>${rfq.matchedSuppliers} qualified</strong></div><div class="rfq-spec"><span>Next step</span><strong>${escapeHtml(rfq.nextStep)}</strong></div></div><div class="rfq-progress">${["Demand normalized","Suppliers invited","Quotes received","Capacity test","Contract","Delivery"].map((label,i)=>`<div class="rfq-progress-step ${i<3?"is-done":i===3?"is-active":""}">${label}</div>`).join("")}</div></div>
      <aside class="broker-card"><div class="broker-profile"><div class="broker-avatar">B17</div><div><strong>${escapeHtml(rfq.broker)}</strong><span>KYB verified · mandate on file · commission disclosed</span></div></div><div class="broker-stats"><div class="broker-stat"><span>30D RFQ volume</span><strong>$3.8M</strong></div><div class="broker-stat"><span>Median fill</span><strong>18.4h</strong></div><div class="broker-stat"><span>Test pass</span><strong>92%</strong></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Authorized access only</strong><span>Broker sees only RFQs under buyer mandate.</span></div></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Separate data series</strong><span>Responses never enter core TMCI or public Available.</span></div></div></div><button class="secondary-button" style="width:100%;margin-top:14px" type="button" data-action="open-rfq-responses">查看私密报价</button></aside></section>
    <section class="section"><div class="section-header"><div><h2>Active Private RFQs</h2><p>独立于公开 Market Depth，仅向获邀供应商开放。</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>RFQ</th><th>Market</th><th>Requirement</th><th>Responses</th><th>Indicative</th><th>Status</th><th>Index treatment</th></tr></thead><tbody>${rfqExamples.map((item)=>`<tr><td><span class="strong">${escapeHtml(item.id)}</span><span class="subline">${escapeHtml(item.title)}</span></td><td>${escapeHtml(item.market)}</td><td>${item.request.oevUsd?compactMoney.format(item.request.oevUsd):escapeHtml(item.request.hardware||"Custom capacity")}</td><td>${item.matchedSuppliers}</td><td>${item.indicativeRange?`${item.indicativeRange.lowMultiple.toFixed(2)}–${item.indicativeRange.highMultiple.toFixed(2)}×`:"Private quotes"}</td><td><span class="badge badge-amber">${escapeHtml(item.nextStep||item.status)}</span></td><td><span class="badge badge-gray">Excluded</span></td></tr>`).join("")}</tbody></table></div></section></div>`;
}

export function renderData() {
  const ms = indexSeries.modelCapacity.series; const gs = indexSeries.gpuPrice.series;
  return `<div class="page"><div class="page-head"><div><div class="eyebrow">Market Data</div><h1>TMCI、TGPI 与 AI Capacity Curve</h1><p>核心指数只使用合格 Lane A 数据；Private RFQ 只形成独立 OTC 指标。所有图表均为 illustrative demo data。</p></div><div class="page-actions"><span class="badge badge-gray">${escapeHtml(marketStats.displayTimestamp)}</span></div></div><div class="metric-grid"><div class="metric-card"><div class="metric-label"><span>Claude TMCI</span><span class="badge badge-green">A</span></div><div class="metric-value">${modelView(modelMarkets[0]).index.toFixed(2)}×</div><div class="metric-context">Lane A only</div></div><div class="metric-card"><div class="metric-label"><span>Composite index</span><span class="trend-down">${marketStats.compositeChange7dPct}%</span></div><div class="metric-value">${marketStats.compositeModelIndex.toFixed(3)}×</div><div class="metric-context">Strictly bucketed demo series</div></div><div class="metric-card"><div class="metric-label"><span>H100 TGPI</span><span class="trend-down">−4.1%</span></div><div class="metric-value">$${gs.h100.at(-1).value.toFixed(2)}</div><div class="metric-context">USD / accelerator-hour</div></div><div class="metric-card"><div class="metric-label"><span>Private RFQ notional</span><span class="badge badge-amber">OTC only</span></div><div class="metric-value">${compactMoney.format(marketStats.indicativeDailyNotionalUsd)}</div><div class="metric-context">Never in core index</div></div></div>
    <section class="section chart-grid"><div class="panel"><div class="section-header"><div><h3>Model Capacity Index · 14D</h3><p>Claude (blue) vs GPT (teal) · reference = 1.00×</p></div><span class="badge badge-gray">Demo</span></div>${lineChart(ms.claude,ms.gpt,"×")}</div><div class="panel"><div class="section-header"><div><h3>Index publication gate</h3><p>不足阈值时显示 Indicative 或 No Print。</p></div></div><div class="lane-stack"><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Settled Lane A trade</strong><span>Core index eligible</span></div><em>Highest weight</em></div><div class="lane-row"><span class="status-dot status-dot-green"></span><div><strong>Firm executable quote</strong><span>Depth only</span></div><em>Live depth</em></div><div class="lane-row"><span class="status-dot status-dot-amber"></span><div><strong>Verified Private RFQ</strong><span>Separate OTC indicator</span></div><em>Never mixed</em></div></div></div></section>
    <section class="section chart-grid"><div class="panel"><div class="section-header"><div><h3>GPU Price Index · 14D</h3><p>H100 (blue) vs H200 (teal) · exact SKU buckets.</p></div><span class="badge badge-gray">USD / h</span></div>${lineChart(gs.h100,gs.h200,"")}</div><div class="panel"><div class="section-header"><div><h3>Methodology metadata</h3><p>每个数字都带样本、时效与置信度。</p></div></div><div class="rfq-specs" style="grid-template-columns:repeat(2,1fr)"><div class="rfq-spec"><span>Window</span><strong>Rolling 7D</strong></div><div class="rfq-spec"><span>Refresh</span><strong>Hourly demo</strong></div><div class="rfq-spec"><span>Statistic</span><strong>Capped VWAP</strong></div><div class="rfq-spec"><span>Cross-check</span><strong>Weighted median</strong></div></div><div class="scheduler-note"><span>ⓘ</span><div>闭源模型只展示 GPU 与 Model Capacity 的价格相关性，不声称可反推其真实成本或利润率。</div></div></div></section></div>`;
}
